### ISSUE TITLE
Config in StructureMap Di Container

### ISSUE THREAD

**Issue by Mansoun** [Sina-Soltani/Parbad#67] opened 2020-04-05 12:13 UTC
Hi.
I'm using mvc5 and StructureMap for DI container. I set my Container for IOnlinePayment  , will create DefaultOnlinePayment instance for inject. But I have a question for Config in Startup.cs and Global.asax
 in your Example, you used Autofac for external DI container. in Autofac you populated the service that configured before. I did all these but confuse for config. I used one of Vahid Nasiri's Project for starting the App and in this his Project, He separated All layers included users and identity 2.
This is very Difficult for me to develop in DI part.
This is the error : http://uupload.ir/files/ymvq_error.png  the Githup uploader doesn't work.

If you help me to do this , i'll will be very grateful. otherwise Thanks a lot again .

**Comment by Sina-Soltani** [comment] 2020-04-05 13:04
Hi,
you don't need to add or configure the DefaultOnlinePayment class or any other classes and interfaces. Parbad do all of them automatically. The problem is your DI library must be compatible with Microsoft DI.

For all DI libraries there is a nuget package which is something like:
`<DI NAME>.Microsoft.DependencyInjection` or `<DI NAME>.Extensions.DependencyInjection`

- StructureMap: [StructureMap.Microsoft.DependencyInjection](https://www.nuget.org/packages/StructureMap.Microsoft.DependencyInjection/)
- Autofac: [Autofac.Extensions.DependencyInjection](https://www.nuget.org/packages/Autofac.Extensions.DependencyInjection/)
- And so on.

Depend on your DI library you must install the nuget package in your project and append [this](https://github.com/Sina-Soltani/Parbad/blob/master/samples/Parbad.Sample.Mvc/Startup.cs#L36) line.

The Parbad MVC sample covers all DI libraries.

By the way, StructureMap is old and the owner does not develop it anymore according to [this](https://jeremydmiller.com/2018/01/29/sunsetting-structuremap/) article. You should use [Lamar](https://jasperfx.github.io/lamar/getting_started/) which is new and similar to the StructureMap.

**Comment by Mansoun** [comment] 2020-04-05 13:39
Thanks. I got it. 
Yes your right about StructureMap.
Thanks again.
I installed StructureMap.Microsoft.DependencyInjection.
But i can not find something to populate parbad services in StructureMap.
In every search I've done, no one mentioned about populate services or I Can't find.
If you know any document or tutorials please share with me ❤️

**Comment by Mansoun** [comment] 2020-04-05 14:31
Well. after a while i found [this](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection) and i realized i used the previews version of StructureMap that doesn't "Populate".
I updated the DI Container but also have Error for casting.
I'm trying to fix this and I will inform you.
Thanks.

**Comment by Sina-Soltani** [comment] 2020-04-07 08:05
Should I close this issue?

**Comment by Mansoun** [comment] 2020-04-07 08:40
Yes. My Problem is solved. I Upgraded my Di Library to the last version and everything good.
Thanks Again ❤️

**Comment by Sina-Soltani** [comment] 2020-04-07 08:43
No problem. Don't forget to like the repository :)

**Closed by Sina-Soltani** 2020-04-07 08:43 UTC
Labels: question
